### ISSUE TITLE
Repository does not exist.

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/htm-css-code-along-3#1] opened 2015-08-13 18:58 UTC
Repository for github.com:learn-co-students/fe-exceptional-realty-web-0915.git dost not exist. Perhaps this should be the htm-css-code-along-3-web-0915 repo?

**Comment by AnnJohn** [comment] 2015-08-19 15:15
@aturkewi that's a repo that you create by following the instructions in the code-along in the htm-css-code-along-3-web-0915 repo. feel free to reach out with any other questions, and if there aren't any, I'll close this issue by 8/21

**Comment by aturkewi** [comment] 2015-08-19 15:54
AnnJohn,

From the video, it seems like the upstream is the new source code that I should be updating my local site to. It sounds like whoever made the video added content to the pages (material that will be styled and broken into columns, ref 55s) since the last exercise. I cannot find this source code and was under the impression that it was the upstream. 

Is it located elsewhere? Should I be adding all of that material on my own?

**Comment by AnnJohn** [comment] 2015-08-19 21:01
Ahh you're right; my mistake. I'll take a look and see what the issue is.

**Comment by AnnJohn** [comment] 2015-08-19 21:09
There's no source code you need to find. Instead in terminal, just enter the command 

git remote add upstream git@github.com:learn-co-students/fe-exceptional-realty-web-0915.git

Does that work?

**Comment by AnnJohn** [comment] 2015-08-24 13:27
Closing issue

**Comment by aturkewi** [comment] 2015-08-25 20:01
AnnJohn, 
I was able to add the remote from your instructions, but when I try and pull from the remote, I get this error:

```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

That's what started my comment on this. I cannot locate this repository using the browser interface. I am not sure that it is correctly posted online. Can you confirm that it is correctly posted and that I have permissions to pull?

Thank you, and sorry for the long wait to reply.

**Comment by aturkewi** [comment] 2015-08-28 13:35
@AnnJohn Not sure if you saw my last message as you marked this closed. I just wanted to throw in another update. I ran into another incoming student for the web-0915 group that had the same problem. We cannot find (or cannot access) the repo that you have provided.

**Comment by AnnJohn** [comment] 2015-08-28 13:45
@aturkewi Thanks for following up. We'll have one of our curriculum developers. instructors look into it asap.

**Comment by AnnJohn** [comment] 2015-08-28 14:06
@aturkewi We updated the Readme and the issue should be resolved. Could you check and let us know? Thanks.

**Comment by aturkewi** [comment] 2015-08-28 14:28
@AnnJohn Thanks for updating this, but I do not believe this is the correct source code for this code along.
If you look at the video location I mentioned earlier on (about 55s in), the presenter talks about about new material added to the page that will later be formatted into a footer with columns. The new material that the video shows is not in this repo on the master branch (and that's the only branch I see). 
Also (not sure if this is related), but when I type in `git reset --hard step-2` I get: 

```
fatal: ambiguous argument 'step-2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by AnnJohn** [comment] 2015-08-28 15:48
Hey @aturkewi can you email our director of faculty, Joe and he should be able to help you out.  joe@flatironschool.com

**Comment by AnnJohn** [comment] 2015-08-28 15:48
@jmburges. Just mentioning you here

**Comment by AnnJohn** [comment] 2015-08-28 18:24
@jongrover  Can you look at this lab which a couple of students have had issues with because of the lab dependencies?

**Closed as completed** 2022-12-14 14:58 UTC
Labels: icebox
